### ISSUE TITLE
Disable clicking on particular state on breadcrumb

### ISSUE THREAD

**Issue by samundrak** [ncuillery/angular-breadcrumb#109]
How can i disable click on particular state like
Home / Contact /Email
Here i want to disabled clicking on Home only Contact and email will be can be clicked

**Comment by abraham-fox** [comment]
Hello, samundrak.
You can mark "Home" step as abstract and force angular-breadcrumb to show it (if you have not already using global option "includeAbstract"):

```javascript
.state( 'abc.home',  { 
    ...
    abstract: true,
    ncyBreadcrumb: {
        ...
        force: true
    }
})
```

so control will render your step using `<span/>` instead of `<a/>`.

Or you can create your own HTML template by simply copying it from angular-breadcrumb.js file - line 185 for bootstrap2 or 192 for bootstrap3. And then provide your own custom variable: 
 
```javascript
.state( 'abc.home',  { 
    ...    
    ncyBreadcrumb: {
        ...
        myCustomVariable: true
    }
})
```

Use it inside your template as `{{ step.ncyBreadcrumb.myCustomVariable }}` with ng-if (or ng-switch) for hiding or disabling some HTML controls.

**Comment by ncuillery** [comment]
I couldn't give a better answer than @abraham-fox :smile:

**Comment by jasbirquoality** [comment]
Hi, devs you can use a similar method like an event.preventDefault() method (in react ). Hope this helps.

My breadcrumb: (In my case, I want the breadcrumb '3' to be unclickable.) 

const handleBreadcrumbClick = (event) => {
    if(event.target.name === '3')
    event.preventDefault()
  }


<Breadcrumb.Item key={index.toString()} name={index.toString()} onClick={handleBreadcrumbClick} href={`/${intentUrl}`}>
                      {breadcrumb}
</Breadcrumb.Item>
