### ISSUE TITLE
Bound labels don't populate on browser refresh

### ISSUE THREAD

**Issue by zpydee** [ncuillery/angular-breadcrumb#42]
I am finding that breadcrumb labels bound to a controller's scope do not rebind on browser refresh.

**Comment by maku** [comment]
Had the same issue on reloading a page. Passing $breadcrumb in the run function (like @Stavrakakis suggested) solved the problem.

**Comment by SantechDev** [comment]
OK, after some more digging, it seems that for me the analysis from @ansorensen was proper. If I check for watchers and only do the check if isAOlderThanB then, the label properly displays.

I've checked the $id from the targetScope and lastViewScope, and the conditions always end up being true. I'm not sure if only relying on that is sufficient. I have no $viewContentLoaded anywhere else in my app so that can't be polluted. However I do have some nested views within children states... Maybe that's why.

Issue is now, how can I port this modification to production..?

**Comment by SantechDev** [comment]
OK, with a bit more digging, it was because I had many ui-view on the same page. My index page looked like this:

```html

  <div ui-view="menu"></div>

      <section class="wrapper">
        <div ui-view="topNav" class="topNav" id="return-top"></div>
        <section>
          <div ui-view="subheader" class="subheader"></div>

          <div ui-view="content" class="main"></div>
        </section>
    </section>
    <nav ui-view="footer" id="footer"></nav>

<div ui-view="root"></div>

```

Thing is, this way the last controllers being created were footer and root. Whereas my content comes from the content view (and its associated controller)

I now use ng-include for the footer as I can't move it, and I moved root to the top of the page as it doesn't display anything. Like so:

```html

  <div ui-view="root"></div>

  <div ui-view="menu"></div>

      <section class="wrapper">
        <div ui-view="topNav" class="topNav" id="return-top"></div>
        <section>
          <div ui-view="subheader" class="subheader"></div>

          <div ui-view="content" class="main"></div>
        </section>
    </section>
    <nav ng-include="'views/navigation/navigationBottom.html'" id="footer"></nav>

```

Hope that helps some of you.

**Comment by mateutek** [comment]
I am using angular-fulstack generator
when installing ncyBreadcrumb
i added it to the navbar component.
After refresh the {{impex.name}} dissappears

**Comment by CaptainYouz** [comment]
Hello,
i have the same issue where i refresh the browser.
The solutions mentionned in this topic didn't work for me.
Does anyone found a patch ?

**Comment by kazinov** [comment]
[This plunker](http://plnkr.co/edit/yeODlzws6gv05tZ7nURd?p=preview) demonstrates the common problem with a footer view.
I created the pull request https://github.com/ncuillery/angular-breadcrumb/pull/99 which suggest the way to solve such a problems.

**Comment by kazinov** [comment]
[This](http://plnkr.co/edit/yeODlzws6gv05tZ7nURd?p=preview) demonstrates common problem when there is an abstract base state which represents a footer

**Comment by rkusuma** [comment]
@kazinov so what is the solution? i'm still get this problem.

**Comment by kazinov** [comment]
@rkusuma 
To solve this issue the property ```ncyBreadcrumbIgnore``` should be set to true on the view controller scope:

```javascript
function ViewController($scope) {
       $scope.ncyBreadcrumbIgnore = true;
}
```
This allows to deal with multiple views related to the same state.

**Comment by patricknazar** [comment]
@Stavrakakis 's solution worked for me but @kazinov 's did not.
