### ISSUE TITLE
Breadcrumb display glitch ? (breadcrumb addition)

### ISSUE THREAD

**Issue by mbret** [ncuillery/angular-breadcrumb#76]
Hi I have a problem with the breadcrumb displaying. the breadcrumb of the previous state is cumulated with the new one everytime I switch on a different state. It happens just 1second and let the place to the correct one finally.

**Comment by mbret** [comment]
Ok it seems that the problem is not really one I said. Now it seems working about the final displaying but everytime I switch on a state, the breadcrumb of the previous state is cumulated with the new one. It happens just 1second and let the place to the correct one.

**Comment by ncuillery** [comment]
Hi, it is a curious and never-seen-before bug. 

I need more information like 
- versions of angular / ui-router / angular-breadcrumb, 
- states configurations,
- ideally a plunker (you can fork [this one](http://plnkr.co/edit/O8oOgnvcJ57k97f1fWRW?p=info))

No error in console ?
It looks like a perf issue. Can you try to add console.log in the module (for example [here](https://github.com/ncuillery/angular-breadcrumb/blob/master/release/angular-breadcrumb.js#L203) and [here](https://github.com/ncuillery/angular-breadcrumb/blob/master/release/angular-breadcrumb.js#L118)) in order to detect infinite loops.

**Comment by ThomasHambach** [comment]
For me it was an issue with missing CSS styles. See https://docs.angularjs.org/api/ngAnimate for more information.

    /* The starting CSS styles for the enter animation */
    .ng-enter {
      transition:0.5s linear all;
      opacity:0;
    }
  
    /* The starting CSS styles for the enter animation */
    .ng-enter.ng-enter-active {
      opacity:1;
    }
  
    .ng-leave {
      opacity:0;
    }
    .ng-leave.ng-leave-active {
      opacity:0;
    }

**Comment by ncuillery** [comment]
@mbret do you use ngAnimate ?

**Comment by mbret** [comment]
@ncuillery I used it, because when I deactivate it, your plugin works fine. I didn't try the @ThomasHambach fix though.

**Comment by ncuillery** [comment]
Related to #40

**Comment by ncuillery** [comment]
I close this.

The module seems to work well with ngAnimate. See https://github.com/ncuillery/angular-breadcrumb/issues/40#issuecomment-209148455
